### ISSUE TITLE
[FEATURE] Set model info & supported swing mode

### ISSUE THREAD

**Issue by BenJamesAndo** [revk/ESP32-Daikin#189]
Hello. Thank you for this wonderful device. I'd like to be able to set the model that's reported in MQTT. Currently it's `<unknow>` or rather not specified at all.
![image](https://github.com/revk/ESP32-Faikin/assets/44917135/f814fac8-b653-4e6c-8f79-f7bfdaf8c9c6)

Does it currently try to detect the model info?
Perhaps if I could set it using something like
```
mosquitto_pub \
  -h 'mqtt.local.' \
  -t 'setting/faikin-1' \
  -m '{"model": FTXS35GVMA}'
```
or `/aircon/set_model_info?model=FTXS35GVMA`

Does Faikin have a list of supported devices and if it doesn't detect it it then defaults to nothing? If so I could provide whatever info you need to get my model officially supported.

Additionally, my unit only supports vertical swing mode. If it's not already possible it would be great to remove `H` and `H+V`

**Comment by revk** [comment]
It tries to auto detect the protocol but does not try to identify the exact model. I think it may get something with X50, I'll have to check.

A setting just to get reported (I assume this is for HA) would not be difficult to add.

**Comment by revk** [comment]
Limiting the swing is another possibility with a setting.

**Comment by BenJamesAndo** [comment]
Yes I'm using it within Home Assistant.
Limiting swing with a setting would be great. If it was additionally exposed via the web UI that would be really nice.

**Comment by revk** [comment]
I have issued a change, use `setting/Faikin/swingmode 2` too  limit to V only.

**Comment by revk** [comment]
As for model, do you know the HA config I need to send to tell it the model?

**Comment by BenJamesAndo** [comment]
I had to do `swingmodes` instead of `swingmode` to get it to work. It works great now, thank you. Perhaps at some point it could be updated to display as Vertical instead of V.


> As for model, do you know the HA config I need to send to tell it the model?

Well this is some of the payload for the Faikin
 homeassistant/climate/F412FA97CDE8/config
```
device:
  identifiers:
    - F412FA97CDE8
  name: F412FA97CDE8
  sw_version: a166f13
  manufacturer: RevK
  configuration_url: http://F412FA97CDE8.local/
```
 and this is for a lightbulb that does display it's model
```
 device:
  identifiers:
    - zigbee2mqtt_0xa4c138a090a3df2a
  manufacturer: Gledopto
  model: Zigbee 4W MR16 Bulb RGB+CCT (pro) (GL-S-004P)
  name: Gledopto Master Light
  sw_version: '20251233'
  via_device: zigbee2mqtt_bridge_0x5cc7c1fffedb426a
```

**Comment by jamofer** [comment]
> It tries to auto detect the protocol but does not try to identify the exact model. I think it may get something with X50, I'll have to check.
> 
> A setting just to get reported (I assume this is for HA) would not be difficult to add.

I use X50 and I can confirm it auto detects the model in my case.

> As for model, do you know the HA config I need to send to tell it the model?
Topic: homeassistant/climate/0C8B9596F4C0/config
```yaml
unique_id: 0C8B9596F4C0
device:
  identifiers:
    - 0C8B9596F4C0
  name: ac411
  model: ADEA71A2VEB <----
  sw_version: ce7cb0d
  manufacturer: RevK
  configuration_url: http://ac411.local/
```
